[tool.poetry]
name = "plate-recognition"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "plate_recognition"}]

[tool.poetry.dependencies]
python = "^3.11"
scrapy = "^2.8.0"
pillow = "^9.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
